var typed2 = new Typed("#wisdom", {
  strings: [
    "They ask where do you feel nice. I say no where. They will find you around and follow you. The platform will say no. The rules of our compnay we can not place that in money guide lines. Then they inform you and better make sure to eat up a candy. Then you put your gloves on and will be taken out. I can not make sure they will listen. Do no tell me or myself.",
    "The headpressure in me feels like old graveyards of elders gathering in houses. The streetcredit will be fought out like rules of sweetlines. Household talk feels like accountancy of mother increase. No right amount of weight like crying kids. Look in yourself like world soccer matches. Think of laptops with no future in the feeling of it.",
    "You and her and this and that. No more trust like flowrs under the ground. Not to grow like corn looking at the sun. Stay now and go then Body not enough if the bank of the sea drift will get to you by eaten offshore oil.",
    "The once ask me who do you know now. Then they realize alone they are in life. Do not ask me anymore or less of how to fall in time. The end.",
    "They ask will you hangout. But they want more. Then go in the room. Scared they will be, but minds are kidding. Be creative. Because I can.",
    "I am being educated live on a live stream.",
    "Stop the awfull.",
    "If I see the face with attention. Will she survive the day alone being alone with me. Should the past comes back in writing. If I being the time bear of choco in the mouth. Give me the taste. SO I can tell her to go for it. No she said. I need something else for the moment.The days are passing by. Not coming back from being ignored. Sweet I was to her. Mean I am by me. So old this version. But Why in line of them all. Many things to find out. So classic in time like a sporting huge paycheck. No I want looking back. In front all my tummy fat. Why you like like. Give it to me now. I am ready. Now work it out. Where to burry the rules. In laws of internet. No more. I said no more.",
    "Will it take hours to come back with the reality. Or maybe money make the world go round like making problems from the start. What is now for me. Enter me. No then tell me flower flower will you fly like a bird.",
    "Let the day start when the sunshine fly over the blue water.Let the day end when the church is on fire on some earth pieces of working company in the age of a child carrying the heavyness of corn pieces to the forrest in the oldest sweetest taste inside of justice in guts worming overractions of them all.",
    "Where to live in the painting!",
    "Where O where",
    "Be here and sleep. Or be there and eat along with the crowd or flying away in yourself being understandfull speeding away tickets in the world of the painting.",
    "The world of you see thing will start here.",
    "Internet games in reality. Like a animal store without wheels.",
    "Look its all nice and wseet what some of you want to figure out. What can you push ahead with products and scaling up real quick. I am waiting a whole lot of time. With money or without money. Do not tell me ever what is right or wrong. The sky can fall down. I will not pull the trigger. Graphic some type in here. Fire and elektricity that was real. You tell me agian what is 0-100 or 0-100 double up. 2x 2x Now who is upset. Framing me with chicking wings. Ok Ok whole lot of bones to chew on",
    "Accident of layers of rules in me. Place that stick in the top level of firm quality of small country that I know. Bi country of internet RULERS. Make the numbers up in 100 years. Now you tell me be quit like the little 0. Nah I prefer no present gift of female looking type or sad stroy of typing like fly closing mouths.",
    "Its a mess! Every single 7 years. Its a mess. Its a MESSSSSSSSSSS",
    "Loyal and *** What a joke.",
    "All day in this chair aint good for the health.",
    "ERRORS",
    "I not OK anymore!",
    "I have typing ERROS. I am a IDIOT!",
    "Warning being made. Like a heart attack. On the way I am standing my grounds. Let me get the llokout. Sugar in my mouth lke knowing I am alone big. Stop push forward like handling graveyards like ship containers. Know how to stop and pull. Came back to slow like meat eaters.",
    "It is about culture in the mind of you. I am so ready! I am ready",
    "I am ready or I am done. Let me know!",
    "I  am looking good again nor not. The self beware of exposing. They know",
    "No look guys girls bots. Who is smart? To get large paychecks. Who is wise to make the calls? Who is cute to have the FUN with. Now listen up and where is my stream? Refresh in time, I am not your guy buddy. I am like a kid. Give it now and dump it later. Take the time to tell me what the teams are. Other wise I will make the call to HUMAN RESOURCES directly when the video is still playing on this PLATFORM. After typing this my heart attack is gone!",
    "Hey you.",
    "It aint right It aint right.",
    "Thank you Thank you. Have a nice day.",
    "Poor broke like skinline caring for co-workers where you at. No yeah No yeah. Make them nuts. CORN TIME.",
    "I have to say no to you. Look into your profile. I can do better then you. Thanks for nothing.",
    "When is it time to find out who your are. Never ever alone or always making them upset. You had me there for a second. But know I know it all like a little seed in the ground. Infusion right infusion right. Make them walkers of no talkers! Make them walkers of no talkers! Where is my money!",
    "Look at me one more time. Money I can not give the system aint ready. What is this creation live from thos place. They will ssay we will learn from you. I will do it with you. Then its over. Internet games! Internet games! Where do you belong. Laws behold the rules after the great wall of coins surrounding you. Now go ahead in time and leave everything behind for some time. But you thoug ness is swimming around.",
    "I want to play pool and swim in the heavy sea. There I was lying to the sky. The sky told me ok I am ready if you are. Remember your picture of greatness. Just for you. But I said sky I can not walk normal no more. The sky told me wait for them. Let them help you out. I said why. The I knew it. Too small of thinking meat. Oversize like water in mouth. Will they give you everything to be complete for some years. I said No for decades. They I ask when is it enogh. If you can not won no more.",
    "Make it work together behave in your human world. Now stay ahead in time with your politics. Time tic tan go. Tic tan go so small. Tic tan go so small. Tic tan go so Big. O well Female up Men down. Dont know where is the work. Live me",
    "Say it aint right. You sit there with your job huh. Well I went in the system huh. Ok now the law is not the pay. Ok I need to know more. Ok no my life is so amazing. No ok the make the CODE! Make the CODE!",
    "This is the return of video, calls or well the talk, my age. Nothing in your mouth like the trip. I am so full of myself. Let them in now. Be the guider. Eating will grow. Yeah you grow.",
    "Water so good like movie.",
    "You and me",
    "So the internet writing are the lies beneath the lies. You pick and choose a human girl or a human boy. You will say stuff and then the alter ego think that the human minds or them inside you will make you world go bigger and rounder. Point one to be made. 24 hours you pick and choose. Another 24 hours your pick and choose. Worth it in time",
    "This is a never ending story. Let the wise men take everthing away. Make fun. Change. But stay away from houses and company House company. Can not breathe",
    "I am not smart when I do not use my theory right. Law treatment escape me huh. Ok One day into long days on this platform. I am a talking machine with a face. Lock me in like napping or cut me out like kidding around for you think you know. Fire Fire. Earn it. Earn it. Elektricity build it build it. Hide yourself from the fire in the household. Hide yourself from the fire in the household. Hide your saving energy from me. Money Money.",
    "Sky Why me Wky Why me.",
    "Internet laws are in line! Internet laws are in line! Persons cannot handle the pressure. More printing coins! Systems will be insilence. I am human. Where I am today will end me the next day. Stop the food stop the food. In the line. One hour wait for telling if you pay. Pay by hour wages. Place the bets. Take responsibility.",
    "Do I have to make excuses for the highest levels what is right or wrong. Or do I have to let them speak for me. Do not force in open culture if you cannot make paychecks. Who are the betrayers here? The so called writers on the internet or the not walking guides in your city or towns. Believe in yourself I can not feel it no more. Not even when the weekend is there around in the U-turn of your life.I know this and that. Use your pressure points for mental attack. I stand by what I write.",
    "Get in line!",
    "You ever saw a bee and you see a dogface in it. Then you know it can be a dogbee. New find and search on the internet one of all here in the streamchat. If that is a company and what they are selling under a brandname. Because after my time spending here. I can tell you know  . To listen to me if you decide to turn the tables to become very well in fairing the wave of commenting. Now split up.",
    "They say do you. Then You wait like the withness you are. Later they wrote it. Now you are paying. Destroy to make up later. Can I have a walk to bow down. No we will fix it for you. Who is there for you if little teams can not be ready. The job.",
    "Somethings are stuck under reality. Go not strong, bring them to the weak.",
    "They think not for themselves. On the way to buy their things. We not alike. Away like animals with high up sounds of where they pretend to stay.",
    "At the moment time passed further in its underground feelings. Waiting not to come over like windbreeze will level up they looking with bad things in going stuff. What to do next when ice cream will not make you go into the water taste.",
    "When you give up. Then you resting. You will not grow up.",
    "So small and innocent, but where are the larger ones.",
    "Together there not longer. See them from there. Closing in. Green too much, nature will be seeing the animals.",
    "The face can cover you in for a while. Soon the sun will not make the moon see each other. The tech x bet will not survive. Who to blame me alone staring in some time. Forget dark choco and milk. Elements to see above in under.",
    "Whisper Whisper, you are not alone. Where to see and where to go. Sleep rest to hide you if i need more. Tasting you from now on will get the works back. No more change. Just go ahead.",
    "Special attention in whisper why o why. Tech whisper why o why. Scream no longer. Your in there alone. Do it with yourself. Eat the whole pie up. You are sure then let me go.",
    "They say place the best teams together. Then you can get one. More doors to bullie over. Let years become wasted so far as you will sit out your sentence. Look again wise you fly. I will not eat you. They will from that place.",
    "Making checks on fools are like shadows falling not to get it done. Low ride of waking up when you can not buy your food stuff of overload.",
    "Complete mess !",
    "meat store!",
    "If you are here that will be terrible the whole day. In a minute you can go. Get a JOB!",
    "The internet is loyal to some. The internet is loyal to a lot. The internet is loyal to know one.",
    "There is plenty to live for. Day for day pass by.",
    "Life passing me by. Do something.",
    "I deserve better.",
    "The problems were not for me. The problems came from myself within. No more, No more.",
    "Nothing is more certain then water crossing. Where do you think you have your drink ready if you think you know them. Try on right. Ok Ok",
    "Laughing alone in this room.",
    "Yeah.",
    "Attention is only for me. First that later influence. No bluiding your outsetting is like connection on a monday. Silence will make me fall asleep alone. I will not put up with it. Is that clear.",
    "I have nothing to say. Get your influence from someone else ok.",
    "Hey I want a 1/24 second skinny girl.",
    "blob",
    "No look I want honest coins. Honey skin in the timeline. With attitude of good in the works. Then I will say to you no. After tasting will be cheap when I look in. Laws and agreements I can order in like time falling. Dont low me down you know why. Almost no real meat eater. Stay vegan and stay in high school.",
    "Yeah meat one day. Drink another day. Work there, work here. Think you sticking it in. But no you have to have all the stocks and then you see your brain is working overtime. The jobs are there dont give up.",
    "I am great you stupid ones!",
    "My name is fake. My name is Georgy.",
    "Leave me alone.",
    "weak down. strong up. reality check",
    "HELLO",
    "I am so tired of nit getting it done",
    "Look at my SKIN.",
    "I am POOR.",
    "Thats it guys girls bots. Have a nice day. Stream off. Bye.",
    "Come back next day  you alone can turn them into. Brhaving not over acting haha cry cry in time fly.",
    "So what. I earned the time with some coins. But every thing that I type can be used against me.",
    "Hey all of you here now Live on the internet and watching this. The last week or maybe 2 weeks in. Was being banned by the girls here on this platform. Some of them enjoy it and some of them dont. But remember I am a real person and the feeling of ordering someone is like drinking and eating. So what I want is? You tell me.",
    "Look listen. If you have a problem. Where do you go. But if you dont admit. Will tech business will be a cold raindrop. So even after the sun can turn off. Then the moon can maybe sing. Here is really the thing after all this. Then you have to figure out to take a piece of cake and then eat it. So place it in your tummy yummy.",
    "You write it down. big mouth.",
    "I know movies ok.",
    "Hey how do they living this out now or not.",
    "Hey I feel like you know.",
    "Too much heat here. Like the fat will not fall off.",
    "She lleft me",
    "great one hmmmmmmmmmmmmmmmmmm",
    "Whatever I am in a conversation here!",
    "Ok and I am sitting alone. Round of applaus!",
    "Blue drink with chips and serranoham.",
    "Get out of here with that raid!",
    "Your problem!",
    "Are there any benefits if you are the leader.",
    "Go away Go away",
    "Can everyone just leave this streamroom now and never ever come back again.",
    "Wait for it, Wait for it. Attack the market now. Do it now.",
    "100 down to ZERO. HELLO!",
    "HELLO!!!!!!!!!!!",
    "Who does what, Who does this, No more waiting. Choose and pick a product!",
    "Dont waste time!",
    "Make it happen!",
    "Will it go wrong. To the judge. To the court! In the walls. This place slow mode like 2x Internet reels in the wheeling driving car. Buy or sell.",
    "ME me me sheeps!",
    "What a music genius!",
    "Internet real or living lies to stop.",
    "TOAST! burn the BREAD!",
    "Get the job. Get the job. Get the job. Get the job.",
    "It is time too RISE up. Dont pay no more! Just become.",
    "They learn they said. But NO they accept more. Time to change while making it right. Turn left then and get it in slow.",
    "If they see me looking in here, they need me too talk it over. Dont lecture me they said. But know the world will be not in place. Time will be accepting more then it can swell up. No more fatties. But keep it where it was.",
    "Sleeping over like houseparty. Not here like pizza slices! DO IT NOW!",
    "PLATFORM ACTIVATED!",
    "Grow up like pay me!",
    "Stranger talk, who wants it. NA like jobs in. Stop not!",
    "Talk meat now!",
    "Always about do you know more. Status control filling in dust blanks like news articles. Be not there if your not doing it my way. Rol along like big choco. Now you do it.",
    "At one point you dont know what to do anymore.",
    "HE IS NUTS!",
    "I GIVE UP!!!!",
    "There you go! NOW DO IT!",
    "DO IT NOW!",
    "Good and bad I know that like memory back. Good to know you now. Back in line like credit. System down like running backs. Sweet juice too small cant give back. Little fat chubby one eating it out like a strandwalker are in graving. Rent due paid in pay cant get it in the forrest. Court of law like jellyfish stingers. Surviving attitude of defending the wall. Broke still silence like black coffee.",
    "CHOCO BIG",
    "OMG",
    "12345678910",
    "you now and you then. What now.",
    "I dunno",
    "Good job.",
    "No good day.",
    "Where is the energy!",
    "More chicken with maple syrup.",
    "You know why sometimes I type when live on stream. Well because I can.",
    "I was bored so I was typing too big.",
    "They say pay me. Keep it deep in there. When time is up. They will look over it. Now they think they fly. But not one will change humans as far sky can reach myself out there.",
    "They say place the best teams together. Then you can get one. More doors to bullie over. Let years become wasted so far as you will sit out your sentence. Look again wise you fly. I will not eat you. They will from that place.",
    "Yeah Yeah",
    "When the glacet water comes over , then you know you are not the one.",
    "No more food drink nature",
    "LV - LS",
    "After one question I knew it.",
    "I am being framed into a reality of history between one stream and another and that will not be the right choice of all the attention that be left here today alone for me.",
    "The headpressure in me feels like old graveyards of elders gathering in houses.",
    "The streetcredit will be fought out like rules of sweetlines.",
    "Household talk feels like accountancy of mother increase.",
    "No right amount of weight like crying kids.",
    "Look in yourself like world soccer matches.",
    "Think of laptops with no future in the feeling of it.",
    "It feels so fake if I get female attention here.",
    "Like if the upload of the video was real in this platform.",
    "Not right.",
    "You want to fine me in! I am not a outlet store here of you stock dumping writing of exe laptops.",
    "I know if you go in to it.",
    "You will get lost. But One or a coule of words will get thee deed done.",
    "Now its over like being fine with no coins on the way.",
    "Laptop in time on spamming like fish around eating me alive. ",
    "The walk in the sun after some snow.",
    "You will be used or you gonna get used.",
    "Short talk will not get to know the real world of how it spin in yourself alone.",
    "Internet games.",
    "Expression of writing aint getting it done.",
    "They just want more.",
    "The mean look, the sweet voice.",
    "Thanks for nothing proceeding humans.",
    "Pressure tell me where. Tear pressure. Tear pressure. Where smile pressure smile pressure. Boiling water. I need that. Fine, it is yours now.",
    "The next stage you know now.",
    "Too late for you path of choice.",
    "I am not a punch bag of dirt for you.",
    "Fine me now and later make your time content.",
    "So long to wait for it in time.",
    "Do not expect the lines of who you know will be your worth of fining for no reason.",
    "The ops of you will never see.",
    "Let the day start when the sunshine fly over the blue water.Let the day end when the church is on fire on some earth pieces of working company in the age of a child carrying the heavyness of corn pieces to the forrest in the oldest sweetest taste inside of justice in guts worming overractions of them all.",
    "Look its all nice and wseet what some of you want to figure out.",
    "What can you push ahead with products and scaling up real quick.",
    "I am waiting a whole lot of time. With money or without money.",
    "Do not tell me ever what is right or wrong. The sky can fall down.",
    "I will not pull the trigger.",
    "Graphic some type in here.",
    "Fire and elektricity that was real.",
    "You tell me agian what is 0-100 or 0-100 double up. 2x 2x Now who is upset.",
    "Framing me with chicking wings.",
    "Ok Ok whole lot of bones to chew on",
    "Accident of layers of rules in me.",
    "Place that stick in the top level of firm quality of small country that I know.",
    "Bi country of internet RULERS.",
    "Make the numbers up in 100 years.",
    "Now you tell me be quit like the little 0.",
    "Nah I prefer no present gift of female looking type or sad stroy of typing like fly closing mouths.",
    "Warning being made.",
    "Like a heart attack.",
    "On the way I am standing my grounds.",
    "Let me get the llokout.",
    "Sugar in my mouth lke knowing I am alone big.",
    "Stop push forward like handling graveyards like ship containers.",
    "Know how to stop and pull.",
    "Came back to slow like meat eaters.",
    "I am looking good again nor not. The self beware of exposing. They know",
    "Is this painting wrong. I know wrong. U turn.",
    "No look guys girls bots. Who is smart?",
    "To get large paychecks.",
    "Who is wise to make the calls? Who is cute to have the FUN with.",
    "Now listen up and where is my stream?",
    "Refresh in time, I am not your guy buddy.",
    "I am like a kid.",
    "Give it now and dump it later.",
    "Take the time to tell me what the teams are.",
    "Other wise I will make the call to HUMAN RESOURCES directly when the video is still playing on this PLATFORM.",
    "After typing this my heart attack is gone!",
    "Look at me one more time.",
    "Money I can not give the system aint ready.",
    "What is this creation live from thos place.",
    "They will ssay we will learn from you.",
    "I will do it with you. Then its over.",
    "Internet games! Internet games!",
    "Where do you belong. Laws behold the rules after the great wall of coins surrounding you.",
    "Now go ahead in time and leave everything behind for some time. But you thoug ness is swimming around.",
    "I want to play pool and swim in the heavy sea.",
    "There I was lying to the sky. The sky told me ok I am ready if you are.",
    "Remember your picture of greatness.",
    "Just for you.",
    "But I said sky I can not walk normal no more.",
    "The sky told me wait for them.",
    "Let them help you out.",
    "I said why. The I knew it.",
    "Too small of thinking meat.",
    "Oversize like water in mouth.",
    "Will they give you everything to be complete for some years.",
    "I said No for decades. They I ask when is it enogh. If you can not won no more.",
    "When is it time to find out who your are Never ever alone or always making them upset.",
    "You had me there for a second.",
    "But know I know it all like a little seed in the ground.",
    "Infusion right infusion right.",
    "Make them walkers of no talkers! Make them walkers of no talkers!",
    "Where is my money!",
    "Poor broke like skinline caring for co-workers where you at.",
    "No yeah No yeah.",
    "Make them nuts.",
    "CORN TIME.",
    "So the internet writing are the lies beneath the lies.",
    "You pick and choose a human girl or a human boy.",
    "You will say stuff and then the alter ego think that the human minds or them inside you will make you world go bigger and rounder.",
    "Point one to be made.",
    "24 hours you pick and choose. Another 24 hours your pick and choose. Worth it in time",
    "This is a never ending story.",
    "Let the wise men take everthing away. Make fun. Change. But stay away from houses and company",
    "Make them around in the internet. Discord,Skype, Zoom. Where they AT!",
    "Do I have to make excuses for the highest levels what is right or wrong. Or do I have to let them speak for me.",
    "Do not force in open culture if you cannot make paychecks.",
    "Who are the betrayers here?",
    "The so called writers on the internet or the not walking guides in your city or towns.",
    "Believe in yourself I can not feel it no more. Not even when the weekend is there around in the U-turn of your life.I know this and that.",
    "Use your pressure points for mental attack.",
    "I stand by what I write. ",
    "You ever saw a bee and you see a dogface in it. Then you know it can be a dogbee.",
    "New find and search on the internet one of all here in the streamchat.",
    "If that is a company and what they are selling under a brandname.",
    "Because after my time spending here. I can tell you know  . To listen to me if you decide to turn the tables to become very well in fairing the wave of commenting. Now split up.",
    "The most part of waking is being me like 1/24 second day. Then after that I will wake again and I be the 1/24 second type of guy. And after that I will STOP!",
    "I can't have air in my lungs.",
    "1/24 seconds left.",
    "For the underworld and the upper world.",
    "I am so small like 1/24 second type of guy.",
    "Now the basics are all converted in this SUNDAY!",
    "dotquestionmark do it!!",
    "Write a book today one of you",
    "You guys girls bots wanna know the world. 1.social media.2.2021 internet STOP.3.Invest.4Go get it.5.Get in line.",
    "They say do you.",
    "Then You wait like the withness you are.",
    "Later they wrote it. Now you are paying. Destroy to make up later.",
    "Can I have a walk to bow down.",
    "No we will fix it for you.",
    "Who is there for you if little teams can not be ready. The job.",
  ],
  typeSpeed: 40,
  backSpeed: 5,
  smartBackspace: true,
  loop: true,
  shuffle: true,
  backDelay: 2000,
  startDelay: 2000,
});

// force the start of cursor animation while the `startDelay` is ticking
if (typed2.cursor != null) {
  // can't use `toggleBlinking(true)` here, as it has some extra checks
  // whether animation has started...which defeats the purpose
  typed2.cursor.classList.add("typed-cursor--blink");
}
